definitions:
  restapi.AuthDto:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: auth for token
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/restapi.AuthDto'
      produces:
      - application/json
      responses:
        "200":
          description: "true"
          schema:
            type: boolean
      summary: auth for token
      tags:
      - auth
  /users:
    get:
      consumes:
      - application/json
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: "true"
          schema:
            type: boolean
      summary: Get all users
      tags:
      - users
swagger: "2.0"
